build:
  maxIssues: 10

style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: true
    maxLineLength: 120
  WildcardImport:
    active: true

comments:
  active: false

complexity:
  TooManyFunctions:
    active: true
    thresholdInFiles: 20
    thresholdInClasses: 20
    thresholdInInterfaces: 20
    thresholdInObjects: 20
    thresholdInEnums: 10

exceptions:
  TooGenericExceptionCaught:
    active: false
  SwallowedException:
    active: false

performance:
  active: true

potential-bugs:
  active: true

naming:
  active: true
  FunctionNaming:
    functionPattern: "[a-zA-Z][a-zA-Z0-9]*"
  VariableNaming:
    variablePattern: "[a-zA-Z][a-zA-Z0-9]*"
